using System;
using System.Linq;

namespace Watsonia.QueryBuilder
{
	public enum StatementPartType
	{
		Select,
		GenericSelect,
		Insert,
		GenericInsert,
		Update,
		GenericUpdate,
		Delete,
		GenericDelete,
		Table,
		Column,
		Join,
		Aggregate,
		Exists,
		// TODO: Rename that!
		ConstantPart,
		OrderByField,
		BinaryOperation,
		UnaryOperation,
		ConditionalCase,
		CoalesceFunction,
		DateDifferenceFunction,
		DateNewFunction,
		DatePartFunction,
		DateAddFunction,
		NumberAbsoluteFunction,
		NumberCeilingFunction,
		NumberFloorFunction,
		NumberNegateFunction,
		NumberRoundFunction,
		NumberTruncateFunction,
		NumberSignFunction,
		NumberPowerFunction,
		NumberRootFunction,
		NumberExponentialFunction,
		NumberLogFunction,
		NumberLog10Function,
		NumberTrigFunction,
		StringIndexFunction,
		StringCompareFunction,
		StringConcatenateFunction,
		StringLengthFunction,
		StringRemoveFunction,
		StringReplaceFunction,
		StringTrimFunction,
		StringToLowerFunction,
		StringToUpperFunction,
		SubstringFunction,
		ConditionPredicate,
		Parameter,
		ConvertFunction,
		ConditionExpression,
		Condition,
		ConditionCollection,
		RowNumber,
		LiteralPart,
		ScalarField,
		FieldCollection,
		SelectExpression,
		UserDefinedFunction
	}
}
